apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-stack
  namespace: opentelemetry-operator-system
spec:
  chart:
    spec:
      chart: opentelemetry-kube-stack
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
      version: "0.4.1"
  interval: 1m
  releaseName: opentelemetry-kube-stack
  values:
    # values.yaml content here
    # cluster_name will be patched via Kustomize overlays
    clusterName: cluster_name