apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-stack # Match the name from the base helmrelease.yaml
spec:
  values:
    clusterName: cluster_blue
    collectors:
      daemon:
        config:
          receivers:
            prometheus/podmonitor:
              config:
                scrape_configs:
                  - job_name: kubernetes-pods
                    # Here we are modifying the metric_relabel_configs
                    metric_relabel_configs:
                      - action: replace
                        target_label: job_label
                        replacement: kubernetes-apps
                      - source_labels: [ __name__ ]
                        regex: (new-regex-value)  # <-- Modified regex
                        action: keep