---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/monitoring/opentelemetry-kube-stack
patches:
  # cluster_name patch
  - patch: |
      - op: replace
        path: /spec/values/clusterName
        value: test_cluster
    target:
      kind: HelmRelease
      name: opentelemetry-stack
      namespace: opentelemetry-operator-system
  # metrics to keep
  - patch: |
      - op: replace
        path: /spec/values/collectors/daemon/config/receivers/prometheus~1podmonitor/config/scrape_configs/0/metric_relabel_configs
        value: 
          - action: replace
            target_label: job_label
            replacement: kubernetes-apps
          - source_labels: [ __name__ ]
            regex: ^(istio.*|awscni_eni_max|awscni_build_info|envoy_cluster_bind_errors)$
            action: keep
    target:
      kind: HelmRelease
      name: opentelemetry-stack
      namespace: opentelemetry-operator-system